version: "3"
services:
  openssl_nginx:
    container_name: openssl_nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "444:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/snippets:/etc/nginx/snippets
      - ./nginx/parameters:/etc/nginx/parameters
      - ./ssl/certs:/etc/ssl/certs
      - ./ssl/private:/etc/ssl/private
    hostname: ${PARENT_HOSTNAME}
    #domainname: ${HOSTNAME}

# export PARENT_HOSTNAME=$(netsh interface ip show address "Wi-Fi" | grep 'IP Address' | sed -r 's/^.*IP Address:\W*//') # Windows (Wi-Fi)
# export PARENT_HOSTNAME=$(ifconfig | grep "inet " | grep -Fv 127.0.0.1 | awk '{print $2}') # MacOS
# export PARENT_HOSTNAME=$(hostname -I | cut -d ' ' -f 1) # Ubuntu
# docker-compose -f openssl_nginx.yml up -d
